// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_TabView1 = NULL;
lv_obj_t * ui_TabPage1 = NULL;
lv_obj_t * ui_LabelAdresseMAC = NULL;
lv_obj_t * ui_LabelAdresseIP = NULL;
lv_obj_t * ui_Button1 = NULL;
lv_obj_t * ui_LabelButton = NULL;
lv_obj_t * ui_TabPage2 = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TabView1 = lv_tabview_create(ui_Screen1, LV_DIR_TOP, 50);
    lv_obj_set_width(ui_TabView1, 800);
    lv_obj_set_height(ui_TabView1, 480);
    lv_obj_set_x(ui_TabView1, 1);
    lv_obj_set_y(ui_TabView1, -2);
    lv_obj_clear_flag(ui_TabView1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TabPage1 = lv_tabview_add_tab(ui_TabView1, "WiFi");

    ui_LabelAdresseMAC = lv_label_create(ui_TabPage1);
    lv_obj_set_width(ui_LabelAdresseMAC, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelAdresseMAC, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelAdresseMAC, 0);
    lv_obj_set_y(ui_LabelAdresseMAC, 30);
    lv_label_set_text(ui_LabelAdresseMAC, "Adresse MAC :");

    ui_LabelAdresseIP = lv_label_create(ui_TabPage1);
    lv_obj_set_width(ui_LabelAdresseIP, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelAdresseIP, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_LabelAdresseIP, "Adresse IP : ");

    ui_Button1 = lv_btn_create(ui_TabPage1);
    lv_obj_set_width(ui_Button1, 100);
    lv_obj_set_height(ui_Button1, 50);
    lv_obj_set_align(ui_Button1, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelButton = lv_label_create(ui_Button1);
    lv_obj_set_width(ui_LabelButton, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelButton, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelButton, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelButton, "Connect");

    ui_TabPage2 = lv_tabview_add_tab(ui_TabView1, "Bluetooth");

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_TabView1 = NULL;
    ui_TabPage1 = NULL;
    ui_LabelAdresseMAC = NULL;
    ui_LabelAdresseIP = NULL;
    ui_Button1 = NULL;
    ui_LabelButton = NULL;
    ui_TabPage2 = NULL;

}
